=== olsonjj/fdt-5.5-templates/projectTemplates/projectTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://fdt.powerflasher.com/ProjectTemplate"
	xmlns:tns="http://fdt.powerflasher.com/ProjectTemplate">
	<element name="projectTemplate">
		<complexType>
			<sequence>
				<element name="name" type="string"></element>
				<element name="version" type="string"></element>
				<element name="variables" type="tns:Variables" minOccurs="0"
					maxOccurs="1"></element>
				<element name="expressions" type="tns:Expressions"
					minOccurs="0" maxOccurs="1"></element>
				<element name="description" type="string"></element>
				<element name="projectType" type="string"></element>
				<element name="projectPlatforms" type="tns:ProjectPlatforms"
					minOccurs="0" maxOccurs="1"></element>
				<element name="folders" type="tns:Folders"></element>
				<element name="libraries" type="tns:Libraries" minOccurs="0"
					maxOccurs="1"></element>
				<element name="linkedResources" type="tns:LinkedResources"
					minOccurs="0" maxOccurs="1"></element>
				<element name="extensions" type="tns:Extensions" minOccurs="0"
					maxOccurs="1"></element>
				<element name="contentCreation" type="tns:ContentCreation"
					minOccurs="0" maxOccurs="1"></element>
				<element name="antCall" type="tns:AntCall" minOccurs="0"
					maxOccurs="1"></element>
			</sequence>
		</complexType>
	</element>

	<complexType name="Folders">
		<sequence>
			<element name="sourceFolder" type="tns:ConditionString"
				minOccurs="1" maxOccurs="unbounded">
			</element>
			<element name="autoLibFolder" type="tns:ConditionString"
				minOccurs="0" maxOccurs="unbounded"></element>
			<element name="outputFolder" type="string"></element>
		</sequence>
	</complexType>

	<complexType name="ProjectPlatforms">
		<sequence>
			<element name="mobilePlatform" type="string" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="Libraries">
		<sequence>
			<element name="swc" type="tns:Swc" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="Swc">
		<sequence>
			<element name="path" type="string"></element>
			<element name="asDoc" type="string" minOccurs="0"></element>
			<element name="source" type="string" minOccurs="0"></element>
		</sequence>
		<attribute name="if" use="optional" default="true"></attribute>
	</complexType>

	<complexType name="LinkedResources">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="linkedFolder" type="tns:LinkedResource"></element>
			<element name="linkedFile" type="tns:LinkedResource"></element>
		</choice>
	</complexType>

	<complexType name="LinkedResource">
		<sequence>
			<element name="path" type="string"></element>
			<choice>
				<element name="location" type="string"></element>
				<element name="locationURI" type="string"></element>
			</choice>
		</sequence>
		<attribute name="if" use="optional" default="true"></attribute>
	</complexType>


	<complexType name="Extensions">
		<sequence>
			<any processContents="strict" namespace="##other" minOccurs="0"
				maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="Variables">
		<sequence>
			<element name="primaryGroup" type="tns:Group" minOccurs="0"
				maxOccurs="1"></element>
		</sequence>
	</complexType>


	<complexType name="Variable">
		<attribute name="name" use="required" type="string"></attribute>
		<attribute name="label" use="required" type="string"></attribute>
		<attribute name="description" use="optional" default=""
			type="string"></attribute>
		<attribute name="type" use="required"></attribute>
		<attribute name="default" use="required"></attribute>
		<attribute name="enableIf" use="optional" default="true"></attribute>
	</complexType>

	<complexType name="Hyperlink">
		<attribute name="label" use="required" type="string"></attribute>
		<attribute name="description" use="optional" default=""
			type="string"></attribute>
		<attribute name="target" use="required"></attribute>
		<attribute name="style" use="optional" type="string"
			default="" />
		<attribute name="enableIf" use="optional" default="true"></attribute>
	</complexType>

	<complexType name="Group">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="variable" type="tns:Variable"></element>
			<element name="group" type="tns:Group"></element>
			<element name="hyperlink" type="tns:Hyperlink"></element>
		</choice>
		<attribute name="label" use="required" type="string"></attribute>
		<attribute name="description" use="optional" default=""
			type="string"></attribute>
		<attribute name="style" use="optional" type="string"
			default="" />
		<attribute name="enableIf" use="optional" default="true"></attribute>
	</complexType>

	<complexType name="Expressions">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="expression" type="tns:Expression"></element>
			<element name="map" type="tns:Map"></element>
		</choice>
	</complexType>

	<complexType name="Expression">
		<simpleContent>
			<extension base="string">
				<attribute name="name" use="required"></attribute>
				<attribute name="value" use="optional"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="Map">
		<sequence>
			<element name="entry" type="tns:Entry" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="name" use="required"></attribute>
	</complexType>

	<complexType name="Entry">
		<attribute name="key" use="required"></attribute>
		<attribute name="value" use="required"></attribute>
	</complexType>

	<complexType name="ConditionString">
		<simpleContent>
			<extension base="string">
				<attribute name="if" type="string" use="optional" default="true"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="ContentCreation">
		<choice minOccurs="0" maxOccurs="unbounded">
			<element name="folder" type="tns:Folder"></element>
			<element name="file" type="tns:File"></element>
		</choice>
		<attribute name="processFileExtensions" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="Folder">
		<attribute name="src" type="string" use="required"></attribute>
		<attribute name="dest" type="string" use="optional"></attribute>
		<attribute name="recursive" type="string" use="optional"
			default="true"></attribute>
		<attribute name="process" type="string" use="optional"
			default="true"></attribute>
		<attribute name="if" type="string" use="optional" default="true"></attribute>
	</complexType>

	<complexType name="File">
		<attribute name="src" type="string" use="required"></attribute>
		<attribute name="dest" type="string" use="optional"></attribute>
		<attribute name="process" type="string" use="optional"
			default="true"></attribute>
		<attribute name="if" type="string" use="optional" default="true"></attribute>
	</complexType>

	<complexType name="AntCall">
		<attribute name="antFile" type="string" use="required"></attribute>
		<attribute name="if" type="string" use="optional" default="true"></attribute>
	</complexType>

</schema>

=== olsonjj/fdt-5.5-templates/projectTemplates/Web/TDD/description.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:projectTemplate xmlns:tns="http://fdt.powerflasher.com/ProjectTemplate"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fdt.powerflasher.com/ProjectTemplate ../../projectTemplate.xsd">
	<name>Web TDD</name>
	<version>2.5</version>
	<description>${targetPlatform} project type.</description>
	<projectType>${projectType}</projectType>
	<variables>
		<primaryGroup label="">	
			<group label="Application Setup">
				<variable name="appId" label="Default Package:" default="com.powerflasher.SampleApp"
					type="string" />				
				<variable name="htmlTemplate" label="Include HTML Wrapper" default="false" type="boolean" />			
			</group>
			<group label="Project Setup">
				<variable name="selectedSDK" label="Default SDK" default="_highest" type="sdk(3.6,4.9,1.5,4)" />									
				<variable name="useFlex" label="Add Flex Framework" default="false" type="boolean" />
				<variable name="useTDD" label="Add Unit Test Framework" default="false" type="boolean" />								
			</group>
		</primaryGroup>				
	</variables>
	<expressions>
		<expression name="missingSDKWarning">This template requires the Flex 3.6 SDK or later.</expression>
		<expression name="hasMinimumSDK" value="sdkVersionExists('3.6','4.9')"/>
		<expression name="templateError" value="if(!${hasMinimumSDK},${missingSDKWarning},'')"/>				
		<expression name="projectType" value="if(${useFlex},'Web Flex','Web')" />
		<expression name="targetPlatform" value="'Web'" />
		<expression name="preferredSdk" value="${selectedSDK}"/>		
		<expression name="postFileName" value="replaceRegex(${projectName}, '([^\w]+)', '')" />
		<expression name="fileName" value="replaceRegex(${postFileName}, '(^\d+)', '')" />
		<expression name="packageStructure" value="replaceRegex(${appId}, '([.]+)', '/')" />		
		<expression name='isFlex3' value="sdkHasLib(${selectedSDK},'frameworks/libs/framework.swc') &amp;&amp; ${useFlex}"/>		
		<expression name='isFlex4' value="sdkHasLib(${selectedSDK},'frameworks/libs/mx/mx.swc')  &amp;&amp; ${useFlex}"/>		
		<expression name="sourceFolder" value="src" />	
		<expression name="outputFolder" value="bin" />				
		<expression name="autoLibFolder" value="lib" />				
	</expressions>
	<folders>
		<sourceFolder>${sourceFolder}</sourceFolder>
		<sourceFolder>test-src</sourceFolder>
		<outputFolder>${outputFolder}</outputFolder>
		<autoLibFolder>${autoLibFolder}</autoLibFolder>
	</folders>

	<contentCreation processFileExtensions="mxml,xml,launch,properties,as,html">
		<!-- If AS -->
		<file src="as/start.as" dest="${sourceFolder}/${packageStructure}/${fileName}.as" if="!${useFlex}"/>		
		<!-- If Flex 3 -->
		<file src="mxml/blank_mx.mxml" dest="${sourceFolder}/${packageStructure}/${fileName}.mxml" if="${isFlex3}"/>
		<!-- If Flex 4 -->
		<file src="mxml/blank_spark.mxml" dest="${sourceFolder}/${packageStructure}/${fileName}.mxml" if="${isFlex4}"/>	
		
		<!-- If HTML Wrapper -->
		<folder src="html-wrapper" dest="${outputFolder}" if="${htmlTemplate}"
			process="true" recursive="true" />
			
		<!-- If Unit Testing -->Si
		<folder src="unitTesting/swc" dest="${autoLibFolder}" if="${useTDD}" process="true" recursive="true" />
		<file src="as/TestRunner.as" dest="test-src/TestRunner.as" if="${useTDD} &amp;&amp; !${useFlex}"/>
		<file src="mxml/SparkRunner.mxml" dest="test-src/TestRunner.mxml" if="${useTDD} &amp;&amp; ${useFlex}"/>
		<file src="as/SimpleTest.as" dest="test-src/test/SimpleTest.as" if="${useTDD}"/>
					
	</contentCreation>
</tns:projectTemplate>

=== olsonjj/fdt-5.5-templates/projectTemplates/FDT Plugin/ActionPlugin/description.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:projectTemplate xmlns:tns="http://fdt.powerflasher.com/ProjectTemplate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://fdt.powerflasher.com/ProjectTemplate ../../projectTemplate.xsd">
	<name>Action Plugin</name>
	<version>2.5</version>
	<projectType>FDT Plugin</projectType>
	<variables>
		<primaryGroup label="">
			<group label='Project Setup'>
				<variable name="selectedSDK" label="Default SDK" default="_highest" type="sdk(4.5,4.9,2.6,4)" />												
			</group>
		</primaryGroup>
	</variables>
	<expressions>
		<expression name="sourceFolder" value="src" />
		<expression name="outputFolder" value="bin" />
	</expressions>
	<description>FDT Action Plugins are running in the background of FDT. Unlike View or Dialog plugins, they are always active and allow you to create custom code assists like quickfixes or autocompletions, register menu entries or to start up dialogs.</description>
	<linkedResources></linkedResources>
	<folders>
		<sourceFolder>${sourceFolder}</sourceFolder>
		<outputFolder>${outputFolder}</outputFolder>
		<autoLibFolder>lib</autoLibFolder>
	</folders>
	<contentCreation processFileExtensions="as,mxml,xml,launch,html">
		<file src="as/Main.as" dest="src/Main.as" process="true" />
		<file src="as/FdtSwfPluginIcon.as" dest="src/FdtSwfPluginIcon.as" process="true" />
		<folder src="swc" dest="lib" process="true" />
		<folder src="assets" dest="assets" process="true"/>
	</contentCreation>
</tns:projectTemplate>

=== olsonjj/fdt-5.5-templates/projectTemplates/AIR/Blackberry/description.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:projectTemplate xmlns:tns="http://fdt.powerflasher.com/ProjectTemplate"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fdt.powerflasher.com/ProjectTemplate ../../projectTemplate.xsd">
	<name>Blackberry</name>
	<version>2.5</version>
	<description>FDT will setup a basic project targeting the ${targetPlatform} platform. 
		${newline}A description.xml will be copied from the selected SDK to your project and pre populated with the fields set below. A bar-descriptor.xml file will be copied from the Blackberry SDK and added to your project as well. This template has a minimum requirement of the Blackberry plugin, Flex 4.5 and AIR 2.6 SDKs. 
		</description>	<projectType>${projectType}</projectType>
	<variables>
		<primaryGroup label="">	
			<group label="Application Setup">
				<variable name="appId" label="Application ID:" default="com.powerflasher.SampleApp"
					type="string" />
				<variable name="appName" label="Application Title:" default="My Application"
					type="string" />
				<variable name="appVersion" label="Application Version:" default="1.0.0"
					type="string" />				
			</group>
			<group label="Project Setup">
				<variable name="selectedSDK" label="Default SDK"
						default="_highest" type="sdk(4.5,4.9,2.6,4)" />									
				<variable name="addPlaybookLibraries" label="Add Blackberry libraries"
							default="true" type="boolean" />				
				<variable name="useFlex" label="Add Flex Framework"
					default="false" type="boolean" />				
			</group>
		</primaryGroup>				
	</variables>
	<extensions dispensable="blackBerry">
		<blackBerry>
			<createBarDescriptor destDir="bin" if="${targetPlatform}=='BlackBerry'"/>
			<addBBTLibraries if="${addPlaybookLibraries}"/>			
		</blackBerry>
		<mobile>
		      <createDescriptor platform="${targetPlatform}" file="bin/${projectName}-app.xml"/>	
              <setProperty platform="${targetPlatform}" name="ACTIVE" value="true"/>
		      <setDescriptorProperty platform="${targetPlatform}" name="APPNAME" value= "${appName}"/>
		      <setDescriptorProperty platform="${targetPlatform}" name="APPID" value= "${appId}"/>
		      <setDescriptorProperty platform="${targetPlatform}" name="APPFILENAME" value= "${fileName}"/>
		      <setDescriptorProperty platform="${targetPlatform}" name="APPVERSION" value= "${appVersion}"/>
		</mobile>		
	</extensions>	
	<expressions>
		<!--Blackberry error check-->		
		<expression name="missingSDKWarning">This template requires the Flex 4.5 SDK or later.</expression>
		<expression name="hasMinimumSDK" value="sdkVersionExists('4.5','4.9')"/>
		<expression name="templateError" value="if(!${hasMinimumSDK},${missingSDKWarning},'')"/>		
		<expression name="blackBerryWarning">The BlackBerry plugin is not installed. Visit http://fdt.powerflasher.com/blackberry-for-fdt/ to get it.</expression>
		<expression name="blackBerrySdkWarning">The BlackBerry SDK is not installed. Visit http://fdt.powerflasher.com/blackberry-for-fdt/ to get it.</expression>
		<expression name="fail" value="and(${targetPlatform}=='BlackBerry',!hasExtension('blackBerry'))"/>
		<expression name="targetPlatform" value="'BlackBerry'" />
		<expression name="templateError" value="if(${fail},${blackBerryWarning},if(${hasBBTSdk},'',${blackBerrySdkWarning}))"/>		
		<expression name="projectType" value="if(${useFlex},'AIR Mobile Flex','AIR Mobile')" />
		<expression name="postFileName" value="replaceRegex(${projectName}, '([^\w]+)', '')" />
		<expression name="fileName" value="replaceRegex(${postFileName}, '(^\d+)', '')" />
		<expression name="packageStructure" value="replaceRegex(${appId}, '([.]+)', '/')" />		
		<expression name="sourceFolder" value="src" />		
		<expression name="outputFolder" value="bin" />				
		<expression name="autoLibFolder" value="lib" />						
	</expressions>
	<folders>
		<sourceFolder>${sourceFolder}</sourceFolder>
		<outputFolder>${outputFolder}</outputFolder>
		<autoLibFolder>${autoLibFolder}</autoLibFolder>
	</folders>

	<contentCreation processFileExtensions="mxml,xml,launch,properties,as">
		<!-- If AS -->
		<file src="as/start.as" dest="${sourceFolder}/${packageStructure}/${fileName}.as" if="!${useFlex}"/>		
		<!-- If Flex -->
		<file src="mxml/viewNavApp.mxml" dest="${sourceFolder}/${packageStructure}/${fileName}.mxml" if="${useFlex}"/>
		<file src="mxml/homeView.mxml" dest="${sourceFolder}/${packageStructure}/views/HomeView.mxml" if="${useFlex}"/>		
	</contentCreation>
</tns:projectTemplate>

=== olsonjj/fdt-5.5-templates/projectTemplates/FDT Plugin/ViewPlugin/description.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:projectTemplate xmlns:tns="http://fdt.powerflasher.com/ProjectTemplate" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://fdt.powerflasher.com/ProjectTemplate ../../projectTemplate.xsd">
	<name>View Plugin</name>
	<version>2.5</version>
	<projectType>${projectTypeExpression}</projectType>
	<variables>
		<primaryGroup label="">
			<group label='Application Setup'>
				<variable name="viewType" label="View Type" type="enum('Single View','Multiple Views')" default="Single View"/>
			</group>
			<group label='Project Setup'>
				<variable name="selectedSDK" label="Default SDK" default="_highest" type="sdk(3.6,4.9,1.0,4)" />												
				<variable name="useFlex" label="Add Flex Framework" default="false" type="boolean" />				
			</group>
		</primaryGroup>
	</variables>
	<expressions>
		<expression name="preferredSdk" value="${selectedSDK}"/>
		<expression name="eval_views" value="if(${viewType}=='Single View', 'view','views')"/>
		<expression name="sourceFolder" value="src" />
		<expression name="outputFolder" value="bin" />
		<expression name="pluginIconImport" value="concat('FdtSwfPluginIcon;')" />
		<expression name="projectTypeExpression" value="concat('FDT Plugin',if(${useFlex},' Flex',''))" />		
		<expression name='isFlex3' value="sdkHasLib(${selectedSDK},'frameworks/libs/flex.swc')  &amp;&amp; ${useFlex}"/>		
		<expression name='isFlex4' value="sdkHasLib(${selectedSDK},'frameworks/libs/mx/mx.swc')  &amp;&amp; ${useFlex}"/>				
	</expressions>
	<description>This template will create a project named '${projectName}' which contains only the basic libraries to develop and compile a FDT View Plugin.${newline}A FDT View plugin behaves like any other view in FDT, but their UI is build with Actionscript or Flex. It can be used to create utilities that require a UI. View Plugins are only active while opened.</description>
	<linkedResources></linkedResources>
	<folders>
		<sourceFolder>${sourceFolder}</sourceFolder>
		<outputFolder>${outputFolder}</outputFolder>
		<autoLibFolder>lib</autoLibFolder>
	</folders>
	<contentCreation processFileExtensions="as,mxml,xml,launch,html">

		<!-- Always -->
		<file src="as/FdtSwfPluginIcon.as" dest="src/FdtSwfPluginIcon.as" process="true"/>

		<!-- If AS -->
		<file src="as/Main.as" dest="src/Main.as" process="true" if="!${useFlex}" />

		<!-- If Flex 3-->
		<file src="mxml/Main_flex3.mxml" dest="src/Main.mxml" process="true" if="${isFlex3}" />

		<!-- If Flex 4-->
		<file src="mxml/Main.mxml" dest="src/Main.mxml" process="true" if="${isFlex4}" />


		<folder src="swc" dest="lib" process="true" />
		<folder src="assets" dest="assets" process="true"/>
	</contentCreation>
</tns:projectTemplate>
